### PR TITLE
First Japanese Translation PR

### PR DESCRIPTION
**Pull request by konabuta**
# PR into Azure/azureml-cheatsheets

## Checklist

I have:

- [x] read and followed the [contributing guidelines](https://azure.github.io/azureml-cheatsheets/docs/misc/contributing)

## Changes

- enable i18n feature for Japanese translation
- Add Japanese translation to landing page (index.js)

fixes #

### CODE REVIEW

**Comment by aminsaied** [comment]
Thanks for putting this together. We will test this ASAP.

**Comment by fuhuifang** [comment]
Thanks @konabuta for the input. This is what it looks like with `yarn run start -- --locale ja`, and it looks great to me. 
image

My only concern is: if I switch to English ver from here, it will be "page not found" (in Japanese), but I feel like this is what is expected based on https://docusaurus.io/docs/i18n/tutorial

```
Each locale is a distinct standalone single-page-application: it is not possible to start the Docusaurus sites in all locales at the same time.
```

**Comment by konabuta** [comment]
@fuhuifang It works in my github pages. See [this](https://konabuta.github.io/azureml-cheatsheets/). This screenshot is log messages in my github actions workflow.
image

**Comment by slorber** [comment]
Hi, Docusaurus maintainer here.

Yes it works in production deployment, you end up with a static site with all locales (but each locale is a distinct SPA). In dev you can only run one locale at a time and can't switch from one locale to another as easily.

**Comment by konabuta** [comment]
@fuhuifang @aminsaied 
As @slorber commented & discussed at https://github.com/facebook/docusaurus/issues/4998, we can deploy both English & Japanese locales in the same github pages.

**Comment by konabuta** [comment]
@aminsaied  @fuhuifang  Could you check my pull request? thanks.

**Review by fuhuifang — CHANGES_REQUESTED** [review]
Thanks @konabuta for the great work. It looks good to me. Could you pull the latest version of cheatsheet? We made some changes to the contents.

**Comment by konabuta** [comment]
@fuhuifang Thanks for your review. I pull the latest version and add additional translation to markdown files. Could you check again?

**Comment by fuhuifang** [comment]
> @fuhuifang Thanks for your review. I pulled the latest version and added additional translation to markdown files. Could you check again?

Hi @konabuta, I noticed some links still show the English name, and you might want to translate them as well 😄. While most of them work as-is, the following is not responding:
image

**Comment by konabuta** [comment]
@fuhuifang I fixed some link path. Please check again. Thanks !

**Review by konabuta — COMMENTED** [review]
review finished

**Comment by konabuta** [comment]
@fuhuifang Thank you for your review. I don't have write access, could you merge this?

**Comment by fuhuifang** [comment]
> @fuhuifang Thank you for your review. I don't have write access, could you merge this?

@konabuta Sure I just merged it. I also gave write access to you easier future work.

**Pull request merged**
